[package]
name = "bases"
version = "0.2.4"
edition = "2018"
license = "CC0-1.0"
description = "Implementation of jan Misali's number base algorithm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "bases"
